### PR TITLE
Update pyscaffold

### PR DESCRIPTION
**Pull request by wpreimes**
- Update package structure with pyscaffold 3
- Drop support for python 2
- Add ``read_ts`` alias ``read()`` in ``ISMN_Interface``
- Add pypi deployment to travis yml

### CODE REVIEW

**Comment by wpreimes** [comment]
@daberer can you review + merge this?

**Comment by daberer** [comment]
could we address issue #24 and add two lines to readers.py?

**Comment by wpreimes** [comment]
Fixed #24 , but commits are not showing up here yet (see https://github.com/wpreimes/ismn/commit/b2612b93cfbe884409219c1d8ece72cc2ef2f5ea)

**Comment by wpreimes** [comment]
@daberer Ah now they are here, so you can merge, then release ``v0.4`` and check if the pypi upload works

**Comment by wpreimes** [comment]
@daberer thanks for merging, you can also put the new version on pypi, just create a new release (`v0.4`) for this repo here on github and travis should handle the rest.

**Pull request merged**
