### PR TITLE
Add function to initialise different network

### PR DESCRIPTION
**Pull request by wpreimes**
A function that can be called when the reader already exists to change the active networks to read

### CODE REVIEW

**Comment by wpreimes** [comment]
@daberer can you review and merge this? We need it in the qa4sm project (it's basically just restructuring the code), a new minor release afterwards should be made.

**Comment by daberer** [comment]
@wpreimes I cannot merge your pull request because I do not have write access to this repository.

**Comment by wpreimes** [comment]
@sebhahn can change your permissions

**Comment by sebhahn** [comment]
@wpreimes can you check your permission, because you should have admin access

**Comment by wpreimes** [comment]
@sebhahn I can merge my pull requests, but I would rather have someone from ismn (i.e. @daberer) do that.

**Comment by sebhahn** [comment]
@wpreimes you are part of the core team, i.e. you should be able to change permissions

**Comment by wpreimes** [comment]
Right, thanks

**Pull request merged**
